- name: Install To-Do App on new web servers
  hosts: webservers
  remote_user: ec2-user

  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - python3
      become: yes
    - name: Install poetry
      ansible.builtin.shell:
        cmd: curl -sSL https://install.python-poetry.org | python3 -