- name: Install To-Do App on new web servers
  hosts: webservers
  remote_user: ec2-user
  vars_prompt:
    - name: trello_key  
      prompt: Enter the trello key
      private: true
    - name: trello_token
      prompt: Enter the trello token
      private: true

  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - python3
      become: yes
    - name: Install poetry
      ansible.builtin.shell:
        cmd: curl -sSL https://install.python-poetry.org | python3 -
    - name: Create directory for the To-Do App code
      ansible.builtin.file:
        path: /opt/todoapp
        state: directory
      become: yes
    - name: Get the latest version of your code with Git
      ansible.builtin.git:
        repo: 'https://github.com/shaylipatel/DevOps-Course-Starter.git'
        dest: /opt/todoapp
        version: exercise-4
      become: yes
    - name: Install project dependencies
      ansible.builtin.command:
        chdir: /opt/todoapp
        cmd: /home/ec2-user/.local/bin/poetry install
      become: yes
    - name: Create a .env file on the host
      ansible.builtin.template:
        src: /home/ec2-user/.env.j2
        dest: /opt/todoapp/.env
      become: yes
    - name: Copy todoapp.service file to managed hosts
      ansible.builtin.copy:
        src: /home/ec2-user/todoapp.service
        dest: /etc/systemd/system/todoapp.service
      become: yes
   